# Apply patch
git am 0001-SYCL-HIP-PIM-Add-PIM-device-to-HIP-plugin.patch
git am 0002-SYCL-HIP-PIM-Integrate-PIM-memory-management-into-DP.patch
git am 0003-SYCL-HIP-PIM-Launch-PIM-SDK-operations-through-PI.patch
git am 0004-SYCL-PIM-Implement-infrastructure-for-pim_handler.patch
git am 0005-SYCL-PIM-Implementation-of-pim_accessor.patch
git am 0006-SYCL-PIM-Implement-PIM-operations.patch
git am 0007-SYCL-PIM-Add-rectangular-copy-read-write-for-PIM-to-.patch
git am 0008-SYCL-PIM-Pass-additional-layout-information-to-PIM-m.patch
git am 0009-SYCL-PIM-Add-support-for-PIM-ops-on-host-device.patch
git am 0010-SYCL-PIM-Add-PIM-device-selector.patch
git am 0011-SYCL-PIM-Implementation-of-pim_queue.patch
git am 0012-SYCL-PIM-Integrate-PIM-SDK-PIMLibrary.patch
git am 0013-SYCL-PIM-Eliminate-repeated-kernel-construction-for-.patch
git am 0014-SYCL-PIM-Provide-more-accurate-information-about-PIM.patch
git am 0015-SYCL-PIM-Introduce-buffer-unique-ID-for-kernel-cache.patch
git am 0016-Adjust-patch.patch
git am 0017-Delete-debug-msg.patch 
